require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TempupsController do

  # This should return the minimal set of attributes required to create a valid
  # Tempup. As you add validations to Tempup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "upname" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TempupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tempups as @tempups" do
      tempup = Tempup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tempups).should eq([tempup])
    end
  end

  describe "GET show" do
    it "assigns the requested tempup as @tempup" do
      tempup = Tempup.create! valid_attributes
      get :show, {:id => tempup.to_param}, valid_session
      assigns(:tempup).should eq(tempup)
    end
  end

  describe "GET new" do
    it "assigns a new tempup as @tempup" do
      get :new, {}, valid_session
      assigns(:tempup).should be_a_new(Tempup)
    end
  end

  describe "GET edit" do
    it "assigns the requested tempup as @tempup" do
      tempup = Tempup.create! valid_attributes
      get :edit, {:id => tempup.to_param}, valid_session
      assigns(:tempup).should eq(tempup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tempup" do
        expect {
          post :create, {:tempup => valid_attributes}, valid_session
        }.to change(Tempup, :count).by(1)
      end

      it "assigns a newly created tempup as @tempup" do
        post :create, {:tempup => valid_attributes}, valid_session
        assigns(:tempup).should be_a(Tempup)
        assigns(:tempup).should be_persisted
      end

      it "redirects to the created tempup" do
        post :create, {:tempup => valid_attributes}, valid_session
        response.should redirect_to(Tempup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tempup as @tempup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tempup.any_instance.stub(:save).and_return(false)
        post :create, {:tempup => { "upname" => "invalid value" }}, valid_session
        assigns(:tempup).should be_a_new(Tempup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tempup.any_instance.stub(:save).and_return(false)
        post :create, {:tempup => { "upname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tempup" do
        tempup = Tempup.create! valid_attributes
        # Assuming there are no other tempups in the database, this
        # specifies that the Tempup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tempup.any_instance.should_receive(:update_attributes).with({ "upname" => "MyString" })
        put :update, {:id => tempup.to_param, :tempup => { "upname" => "MyString" }}, valid_session
      end

      it "assigns the requested tempup as @tempup" do
        tempup = Tempup.create! valid_attributes
        put :update, {:id => tempup.to_param, :tempup => valid_attributes}, valid_session
        assigns(:tempup).should eq(tempup)
      end

      it "redirects to the tempup" do
        tempup = Tempup.create! valid_attributes
        put :update, {:id => tempup.to_param, :tempup => valid_attributes}, valid_session
        response.should redirect_to(tempup)
      end
    end

    describe "with invalid params" do
      it "assigns the tempup as @tempup" do
        tempup = Tempup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tempup.any_instance.stub(:save).and_return(false)
        put :update, {:id => tempup.to_param, :tempup => { "upname" => "invalid value" }}, valid_session
        assigns(:tempup).should eq(tempup)
      end

      it "re-renders the 'edit' template" do
        tempup = Tempup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tempup.any_instance.stub(:save).and_return(false)
        put :update, {:id => tempup.to_param, :tempup => { "upname" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tempup" do
      tempup = Tempup.create! valid_attributes
      expect {
        delete :destroy, {:id => tempup.to_param}, valid_session
      }.to change(Tempup, :count).by(-1)
    end

    it "redirects to the tempups list" do
      tempup = Tempup.create! valid_attributes
      delete :destroy, {:id => tempup.to_param}, valid_session
      response.should redirect_to(tempups_url)
    end
  end

end
